-- Check Management Application Database Schema
-- Migration: 003_admin_and_registration_codes.sql
-- Adds admin role support and registration code system

-- Add is_admin column to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE NOT NULL;

-- Create registration_codes table for managing user registration codes
CREATE TABLE IF NOT EXISTS registration_codes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code VARCHAR(50) UNIQUE NOT NULL,
    expiry_time TIMESTAMP NOT NULL,
    created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    used_by UUID REFERENCES users(id) ON DELETE SET NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_registration_codes_code ON registration_codes(code);
CREATE INDEX IF NOT EXISTS idx_registration_codes_created_by ON registration_codes(created_by);
CREATE INDEX IF NOT EXISTS idx_registration_codes_used_by ON registration_codes(used_by);
CREATE INDEX IF NOT EXISTS idx_registration_codes_expiry_time ON registration_codes(expiry_time);
CREATE INDEX IF NOT EXISTS idx_registration_codes_is_active ON registration_codes(is_active);
CREATE INDEX IF NOT EXISTS idx_users_is_admin ON users(is_admin);

-- Trigger to automatically update updated_at for registration_codes
CREATE TRIGGER update_registration_codes_updated_at BEFORE UPDATE ON registration_codes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Create a default admin user (password: admin123 - should be changed immediately)
-- Note: This uses a default password hash. In production, generate a proper hash.
-- For now, we'll create a script to set up the admin user properly
COMMENT ON TABLE registration_codes IS 'Stores registration codes generated by admins for user registration';
COMMENT ON COLUMN registration_codes.code IS 'Unique registration code that users must provide during registration';
COMMENT ON COLUMN registration_codes.expiry_time IS 'Timestamp when the code expires';
COMMENT ON COLUMN registration_codes.created_by IS 'Admin user who created this registration code';
COMMENT ON COLUMN registration_codes.used_by IS 'User who used this code for registration (null if unused)';
COMMENT ON COLUMN registration_codes.used_at IS 'Timestamp when the code was used';
COMMENT ON COLUMN registration_codes.is_active IS 'Whether the code is still active (can be deactivated without deleting)';

